name: presensi_marsa
description: Aplikasi Presensi SMK Ma'arif 9 Kebumen
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # WebView
  webview_flutter: ^4.7.0
  webview_flutter_android: ^3.16.0
  webview_flutter_wkwebview: ^3.13.0

  # Permission handling
  permission_handler: ^11.3.0

  # Notifikasi lokal
  flutter_local_notifications: ^17.2.2

  # Lokasi
  geolocator: ^12.0.0

  # Utilitas
  connectivity_plus: ^6.0.3
  shared_preferences: ^2.2.3

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/logo.png
